-- This module coordinates IO and Brick events; optimizing its large state
-- machine costs considerably more than it benefits this non-rendering path.
{-# OPTIONS_GHC -O0 -Wno-unused-imports #-}

-- | Retained fullscreen terminal application and its session bridge.
module Agent.CLI.TUI.App
    ( FullscreenInputBuffer
    , FullscreenRuntime
    , advanceCompletionFlashes
    , agentEntryWindow
    , agentPaneEntryLimit
    , agentPaneVisible
    , backgroundActivityText
    , completionFlashTransitions
    , completionRequiresRedraw
    , conversationScrollbarRenderer
    , choiceRowColumns
    , choiceClosesOnUiTransition
    , drawApp
    , elapsedMillisSince
    , appEventLogicalBytes
    , emitUiEvent
    , enqueueAppEvent
    , externalUrlCommand
    , launchExternalUrlCommand
    , hasQueuedFullscreenInput
    , initialFullscreenAppState
    , mergeConversationView
    , motionDemandFor
    , motionDemandForTerminalFocus
    , motionModeForTerminalFocus
    , lambdaArtWidget
    , quickStartRows
    , quickStartVisible
    , quickStartWideVisible
    , startupCapabilityLines
    , nativeProgressKeepaliveDue
    , nextMotionSchedule
    , newFullscreenInputBuffer
    , newFullscreenRuntime
    , newFullscreenRuntimeWithSyntaxLoader
    , selectedAgentConversation
    , loadSyntaxHighlighterForRuntime
    , queuedFullscreenInputDisplays
    , readFullscreenLine
    , readFullscreenLineWithCatalog
    , readFullscreenLineWithModels
    , readFullscreenLineOr
    , readFullscreenLineOrWithCatalog
    , readFullscreenLineOrWithModels
    , repositoryHeaderText
    , submittedImagePreviewByteBudget
    , submittedImagePreviewCountBudget
    , retainSubmittedImagePreviewsForBlocks
    , previewLogicalEncodedBytes
    , resumeSearchCursorColumn
    , onboardingVisibleRowIndices
    , requestFullscreenPermission
    , requestFullscreenChoice
    , requestFullscreenChoiceWithBody
    , requestFullscreenFilterChoice
    , requestFullscreenOnboarding
    , requestFullscreenResume
    , requestFullscreenSecret
    , requestFullscreenText
    , runFullscreen
    , commitFullscreenImagePreviews
    , commitFullscreenHistoryTurn
    , beginFullscreenLiveHistory
    , clearFullscreenHistorySource
    , reloadFullscreenHistorySource
    , setFullscreenHistorySource
    , setFullscreenSessionActions
    , fullscreenBounds
    , fullscreenVtyConfig
    , fullscreenSurface
    , fullscreenApp
    , wrapFullscreenKeyboardVty
    , wrapMarkdownLinkCursorVty
    , withTrackedVtyBuilder
    , setFullscreenImagePreviews
    , setFullscreenWindowTitle
    , showFullscreenToolImage
    , toolImageBlockId
    , applyStoredFullscreenWindowTitle
    , applyStoredMouseCapture
    , mouseCaptureStatus
    , turnCompletionRequiresRedraw
    , syntaxLanguagesForBlocks
    , uiEventRestartsMotionSchedule
    , applyTextPromptEdit
    , applyMetaConsoleEdit
    , isMetaConsoleToggle
    , maskedSecretText
    , normalizeTextOverlayInsertion
    , textOverlayDisplayText
    , withFullscreenSuspended
    ) where


import Agent.CLI.TUI.Types
import Agent.CLI.TUI.Motion
import Agent.CLI.TUI.Render
import Agent.CLI.TUI.LambdaArt
import Agent.CLI.TUI.App.Runtime
import Agent.CLI.TUI.App.Mailbox
import Agent.CLI.TUI.App.History
import Agent.CLI.TUI.App.Reduce
import Agent.CLI.TUI.App.Overlay
import Agent.CLI.TUI.App.Navigation
import Agent.CLI.TUI.App.Event
import Agent.CLI.TUI.App.Run
